Python/django_python/dz7 telegram/magazine/magazine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tel_app.urls'))
]

Python/django_python/dz7 telegram/magazine/tel_app/urls.py
from django.contrib import admin
from django.urls import path, include
from tel_app.views import reg_form, credit_card

urlpatterns = [
    path('reg_form/', reg_form),
    path('pay_form/', credit_card)
]

Python/django_python/dz7 telegram/magazine/tel_app/models.py
from django.db import models


class Categorie(models.Model):
    nameCategories = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return f"{self.nameCategories}"


class Product(models.Model):
    nameProd = models.CharField(max_length=100, unique=True)
    nameCategorie = models.ForeignKey(Categorie, on_delete=models.SET_NULL, null=True)
    value = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.nameProd}"


class Order(models.Model):
    nameProd = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    idUser = models.IntegerField()
    dtOrder = models.DateTimeField()
    value = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=20, decimal_places=2)

    def __str__(self):
        return f"{self.idUser} - {self.nameProd} {self.dtOrder}"


class Contact(models.Model):
    name = models.CharField(max_length=250)
    password = models.CharField(max_length=250)
    email = models.CharField(max_length=250)

    def __str__(self):
        return f"{self.name}"


class Pay(models.Model):
    number = models.IntegerField(null=True)
    name = models.CharField(max_length=100)
    date = models.IntegerField(null=True)
    cvv = models.IntegerField(null=True)

    def __str__(self):
        return f"{self.name}"

Python/django_python/dz7 telegram/magazine/tel_app/forms.py
from django.forms import *


class ContactForm(forms.Form):
    name = CharField(label='name', required=False)
    password = CharField(label='password', required=False)
    email = EmailField(label='email', required=False)


class PayForm(forms.Form):
    number = IntegerField(label='Card number', required=False)
    name = CharField(label='Name', required=False)
    date = IntegerField(label='Date', required=False)
    cvv = IntegerField(label='CVV', required=False)

Python/django_python/dz7 telegram/magazine/tel_app/views.py
from django.shortcuts import render
from tel_app.forms import ContactForm, PayForm
from tel_app.models import Contact, Pay

def reg_form(request):
    form = ContactForm(request.POST)
    if form.is_valid():
        _ = Contact.objects.get_or_create(
            name=form.cleaned_data['name'],
            password=form.cleaned_data['password'],
            email=form.cleaned_data['email']
        )
    return render(request, 'index.html', {'form': form})


def credit_card(request):
    text = ["Card number", "Name", "Date", "CVV/CVN"]
    card = PayForm(request.POST)
    if card.is_valid():
        _ = Pay.objects.get_or_create(
            number=card.cleaned_data['number'],
            name=card.cleaned_data['name'],
            date=card.cleaned_data['date'],
            cvv=card.cleaned_data['cvv']
        )
    return render(request, 'pay.html', {'card': card, 'text': text})

Python/django_python/dz7 telegram/magazine/tel_app/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Send</button>
</form>
</body>
</html>

Python/django_python/dz7 telegram/magazine/tel_app/templates/pay.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>shdgfa</title>
    <link rel="stylesheet" href="../static/pay.css">
    <script src="../static/pay.js"></script>
</head>

<body>
<article>
    <div class="article">
        <div class="card">
            <div class="card-line">
                <p class="card-line-text">CREDIT CARD DETAILS</p>
            </div>
            <form class="credit-card" method="POST">
                {% csrf_token %}
                <div class="card-number">
                    <label><p class="form-text">{{ card.number.label }}</p>{{ card.number }}</label>
                </div>
                <div class="card-name">
                    <label><p class="form-text">{{ card.name.label }}</p>{{ card.name }}</label>
                </div>
                <div class="card-date">
                    <label for="id_date"><p class="form-text">{{ card.date.label }}</p>{{ card.date }}</label>
                </div>
                <div class="card-cvv">
                    <label><p class="form-text">{{ card.cvv.label }}</p>{{ card.cvv }}</label>
                </div>
                <br/>
                <input type="submit" value="Send">
            </form>
        </div>
    </div>
</article>
</body>
</html>